USE regular_db;

CREATE TABLE Danny (
id INTEGER(10) AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL,
quantity INTEGER(10) NOT NULL,
budget INTEGER(10) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Andrew (
id INTEGER(10) AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL,
quantity INTEGER(10) NOT NULL,
budget INTEGER(10) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Josh (
id INTEGER(10) AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL,
quantity INTEGER(10) NOT NULL,
budget INTEGER(10) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Ryan (
id INTEGER(10) AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL,
quantity INTEGER(10) NOT NULL,
budget INTEGER(10) NOT NULL,
PRIMARY KEY (id)
);